### PR TITLE
Include NuMozart

### PR DESCRIPTION
**Pull request by passiweinberger**
Here is all in one :)

### CODE REVIEW

**Comment by passiweinberger** [comment]
new one from #1

**Comment by breznak** [comment]
2000+ files, that's hell of a PR! :wink: 
:+1: thanks!

**Comment by breznak** [comment]
maybe you can put reference to this NuMozart directory in 
- your NuMozart repo
- the main Readme here

**Comment by passiweinberger** [comment]
Well mostly data and a basic frame. Nothing really useful yet, just so that we work with the same stuff ;) ok I ll do that :) 

<div>-------- Original message --------</div><div>From: breznak notifications@github.com </div><div>Date:04/15/2015  22:33  (GMT+01:00) </div><div>To: "nupic-community/nupic.audio" nupic.audio@noreply.github.com </div><div>Cc: Pascal Weinberger passiweinberger@gmail.com </div><div>Subject: Re: [nupic.audio] Include NuMozart (#7) </div><div>
</div>2000+ files, that's hell of a PR!  
 thanks!

**Pull request merged**
