### PR TITLE
Added initial info re. Sparse coding of audio signals

### PR DESCRIPTION
**Pull request by rcrowder**
Outline for sparse coding. Next section to add is outlining alternate kernel functions.

### CODE REVIEW

**Comment by rcrowder** [comment]
@nupic-community/owners This initial pass outlines theory behind sparse coding for audio signals. I'm tempted to say that this is ready for review, with other PR(s) to outline implementation aspects of early (pre-cortical) auditory processing and SDR encoding strategies. If in agreement, can an owner add the appropriate label for review, or merge in. Many thanks.

**Comment by rhyolight** [comment]
The math is over my head. @breznak?

**Comment by rcrowder** [comment]
I forgot to add the expanded introduction from the Wiki :blush: More will be added to describe thoughts on all the SDRs and how they are encoded, but not quite ready yet. And need more adding for short-term digital sequence projects such as NuMozart (cc @passiweinberger).

**Comment by passiweinberger** [comment]
@rcrowder,  like the approach, for short term sequence representation; especially with the midi decoding; I think a event based endocing would be best. Did not really have time to think hard about the entire project. But yes, i think a additional more event-driven rather than frequency/amplitude based decoder is easier and more accurate for .midi files for example. This would also be a easier way to start and the scale up with FFT and 'real' non-discrete audio data

**Comment by rcrowder** [comment]
@passiweinberger  I very much agree that it's easier to follow and visualize the digital processing side, and as such I believe the math should also be partially segregated. With the digital streaming side as an introduction to streaming audio encoding. A place to introduce more digital specific processing methods, such as fast fourier transforms, discrete wavelet transforms, MFCCs, MIDI encoding, etc.

Using a "phase locking amplitude capturing spiking signal encoder" for digital streaming can be done, and provide extra dimensional sparse representations to feed into perception processing. E.g. A package plugin (VST etc) for a software/hardware synthesizer than can capture the main Left and Right digital mixer outputs to feed into the spike encoder for note and transient onset detection. But imo that is a third step to take, with a suggested ordering of;  
1 Digital streaming and encoding (genre detection in nupic.critic, MIDI encoding, polyphonic music, taking advantage of musical structure).
2 Ongoing mammalian auditory scene analysis work, in conjunction with nupic.vision and nupic.studio (particularly owls and bats, and feline beltways).
3+ Other projects, such as expanding the spike encoding for digital streaming.  

@rhyolight I've added the introduction from the wiki. Good to hear if further high level elaboration is required?
@nupic-community/owners Is this appropriate? After multi-decades in industry, I'm unsure if domain and copyright issues arise from plagiarizing others research into this Readme?
@nupic-community/contributors Any Matlab users around that can help me learn this new package to me, and help with table and class creation?

**Comment by rhyolight** [comment]
> @rhyolight I've added the introduction from the wiki. Good to hear if further high level elaboration is required?

High-level elaboration is rarely frowned upon in my world. :smile:

**Comment by rhyolight** [comment]
> Is this appropriate? After multi-decades in industry, I'm unsure if domain and copyright issues arise from plagiarizing others research into this Readme?

We are all siblings in science, standing on the shoulders of giants and all that. :wink: I say let's merge it.

**Comment by breznak** [comment]
really nice :+1:

**Pull request merged**
