### PR TITLE
Include NuMozart project

### PR DESCRIPTION
**Pull request by passiweinberger**

### CODE REVIEW

**Comment by rcrowder** [comment]
@passiweinberger Thanks Pascal. You'll need to ping a nupic-community owner to move this forward (i.e. someone with write access).

**Comment by breznak** [comment]
@passiweinberger @rcrowder thanks guys! 
note: do you want to include it as a sub-project? I think @rhyolight tried the approach at `nupic`, but didn't work well so we moved away from it. 

I'd suggest: Can you prepare NuMozart to be self-contained, that is all code is in `numozart/` root dir? I'll then create a PR that pulls all the commits from there to `nupic.audio`

**Comment by passiweinberger** [comment]
Oki doki :) will take some time though.

**Comment by breznak** [comment]
you can just do `git mv * numozart/` and it will do :wink: 
(well...not really, because you will try to move numozart/ to numozart/, but *="all files but not numozart/")

**Pull request closed without merging**
