### PR TITLE
Pip install

### LINKED ISSUE #24: make this repo pip installable
so it can be conveniently used along nupic. 

It should be possible to install with: 
`python setup.py install` 
which will install content of `nupic/audio/` and make it accessible from anywhere with: 
`python -c 'from nupic.audio.encoders.wave import WAVEncoder'`

### PR DESCRIPTION
**Pull request by rcrowder**
Fixes #24 

@breznak Here's some changes that allow for a import of the WAVEEncoder to not fail. Can you try these changes locally to see if it works for you too?

### CODE REVIEW

**Comment by breznak** [comment]
Thanks @rcrowder ! I've just tested...and still no. 

Let's verify I'm doin' it correctly: 

```
pip uninstall nupic.audio
python setup.py install
python -c "from nupic.audio.encoders.wave import WAVEncoder"
```

**Comment by rcrowder** [comment]
@breznak I used the import taken from the issue, i.e. `python -c 'from nupic.audio.encoders.wave import WAVEncoder'`

**Comment by breznak** [comment]
@rcrowder ah, my bad; edited my post to add `encoders`. 
Still, does not work for me :cry: . Have you tried to uninstall/reinstall to make  sure there are not any leftover files that "help"? 
- I'm running in `virtualenv` but that shouldn't be an issue, as all other nupic projects are in the same env and import fine. 
- I'm calling the python comand (python -c 'from nupic.audio.encoders.wave import WAVEncoder') from "root", i.e. where `setup.py` is.

**Comment by rcrowder** [comment]
:( This does indeed produce a `ImportError: No module named audio` when trying to import a WAVEncoder

**Pull request closed without merging**
