### PR TITLE
SDR Encoding of audio signals

### LINKED ISSUE #20: SDR Encoding of audio signals
A need to explain and implement generic encoder, that can then be made more domain specific.

### PR DESCRIPTION
**Pull request by rcrowder**
Fixes #20 
Initial work on Readme to outline a plan of attack. And for others to jump in and help out.

### CODE REVIEW

**Comment by cogmission** [comment]
1st thought. It should be a composite encoder like the DateEncoder. This way you can vary the emphasis on certain characteristics. Just an initial thought?

**Comment by rcrowder** [comment]
Perfect! Thanks David. Just the info I may lack right now.
I've also added to main repo Readme a report on Spectral Envelopes in Sound Analysis and Synthesis - https://github.com/nupic-community/nupic.audio/blob/master/README.md

**Comment by cogmission** [comment]
Cool! I will try to give it a look this weekend... :+1:

**Comment by passiweinberger** [comment]
Hey :) 
I'm no pro in signal analysis, but from what I learn when working with LFP recordings, there are many dimensions of patterns in digital signals - like music.
I guess a composite is a must, using something like 
a) timeseries itself
b) batches of furiier transforms to give a little higher level overview
C) maybe something along the lines of a delay differential analysis (probably in a batched format as well) to give a multi dimensional representation of the signal.

My fear here is that music and sound in general has a lot of levels of harmony and patterns, we need a way to encode all of them together in one representation to not loose too much and end up with a mess :S 
Thoughts?

**Comment by rcrowder** [comment]
@passiweinberger Thank you Pascal. These answers and questions are great. For reference here's the link to the NuPIC mailing list discussion; http://lists.numenta.org/pipermail/nupic_lists.numenta.org/2015-October/012047.html

**Comment by passiweinberger** [comment]
Ok, thanks :) 
I didn't notice this discussion :o 
Really interesting problem...
In deep learning problems like this are usually solved by what is called data-augmentation, where you successively add different levels of noise and shifts to your data to a) get more training data and b) be more resilient to overfitting.
I guess we could use a similar approach for this problem.

on data-augmentation:

https://www.techopedia.com/definition/28033/data-augmentation

https://wwwf.imperial.ac.uk/~dvandyk/Research/01-jcgs-art.pdf

http://jmlr.org/proceedings/papers/v38/gan15.pdf

Or just Google ;D

---

BE THE CHANGE YOU WANT TO SEE IN THE WORLD ...

**Comment by rcrowder** [comment]
@passiweinberger Thanks, the augmentation and DBN work ties in definitely. I've just dumped on going work into this repo, particularly in the genre classification project.

**Comment by breznak** [comment]
#22 might interest you. 
- I'm not sure if "SDR encoding of sound" is required? As this sounds basically like what HTM could do(?): `sound->digitalize->SP+TM-> SDR of a sequence`

**Pull request merged**
